url: 
baseurl: 

# Site settings
title: Creek Trail Equine
email: karen.k.parham@gmail.com
description: "Creek Trail Equine, Stone Bluff, OK, is a family-owned business offering horse boarding services."


# Team names, titles and social links
people:
- name: Pistol
  pic: pistol
  position: Chief Horse

- name: Choctaw
  pic: choctaw
  position: Tennessee Walker

- name: Martha
  pic: martha
  position: Matriarchal Mouser

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/creektrailequine

# Postal address (add as many lines as necessary)
address:
  - line: 22074 E. 191st St. South
  - line: Haskell, OK 74436

# Build settings
markdown: kramdown
permalink: pretty
